docs/conf.py
hepdata_lib/__init__.py
pylintrc
setup.cfg
setup.py
tests/test_uncertainty.py
tests/test_utilities.py
tests/test_variable.py

The [docs/conf.py](docs/conf.py) is ignored, since it's a configuration file.
Travis-CI seems to randomly fail when importing `yaml` in the linux python2.7 build. I tried installing `libpython-dev` and `libyaml-dev`, but found that they are already there.
Apart from making the code pylint compatible and adding pylint in general, the only real change is using `@property` for the `Variable` and `Uncertainty` classes.
Closes #14

add pylint and make code compatible

---

.travis/setup.sh
hepdata_lib/__init__.py

Works now, `pip3` was the key to success. Disabled `wrong-import-order` warning in `__init__.py`, which appeared on OSX, but not linux. I suspect it came up because yaml is now installed locally.
Regarding merge: Can just squash the commits in the merge.

Fix pyyaml build

---

docs/requirements.txt
hepdata_lib/__init__.py

In current master, RTD installs hepdata_lib from pypi and then shows documentation for that version, no matter which state of the repo it checks out. Fix by removing hepdata_lib from docs/requirements. There was no reason to have it in there in the first place, it's just something that stuck while I was testing stuff.

Make RTD document the right version

---

setup.cfg
setup.py

I'd suggest to remove pylint temporarily to make things work again, and in particular get the documentation to be built. We can add it back at a later stage.
I'll try to get back to it in the next couple of days.
Closes #32

remove pylint temporarily

---

hepdata_lib/__init__.py
setup.py
tests/test_submission.py

Useful for the case where you want to add actual files to the tar ball, e.g. MC configuration cards.
As it is, this supersedes the functionality of the `add_link` function, but I have not removed it for now.

Submission: New function for adding additional resource files.

---

Dockerfile

This can be used for running `hepdata_lib` with jupyter notebooks. I've written it such that it can be used with myBinder. Give it a try:
[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/clelange/hepdata_lib/docker)
Then create a new python2 notebook and just
```
import ROOT
import hepdata_lib
%jsroot on
```
and you should be ready to go.
The next would then be to add a notebook with examples to this repository.

first version of Dockerfile

---

.travis.yml
hepdata_lib/__init__.py
pylintrc
setup.cfg
setup.py
tests/test_rootfilereader.py
tests/test_submission.py

- fix all pylint errors and warnings that were introduced in the meantime
With a clean environment, I managed to get the tests to run on lxplus as well (using `CMSSW_8_0_20` and a virtualenv).
@AndreasAlbert Can you please also try on lxplus and your setup?
Closes #43

Reenable pylint

---

Dockerfile

Otherwise binder fails to create the thumbnails etc. since `convert` doesn't exist.
Test with:
https://mybinder.org/v2/gh/clelange/hepdata_lib/docker_imagemagick?filepath=examples/combine_limits.ipynb

install imagemagick in docker image

---

.travis.yml
.travis/setup.sh
.travis/travis_wait.sh

Basically I'm now just installing all ROOT dependencies first, then download a tarball of my installation from CERN and move that into the right place. Installing via homebrew takes more than the allowed 50 minutes since ROOT needs to be compiled from source...
The `travis_wait` stuff is nice to have (see https://github.com/clelange/hepdata_lib/compare/travis_wait?expand=1#diff-a677667c17d131d7fe128bf3b226afe9R14) for usage, not needed for this PR, but could be useful at a later stage for long-running tests.
Please squash-merge.

Fix MacOS ROOT python3 installation for TravisCI

---

.travis/setup.sh
docs/setup.rst
setup.py

Require pyyaml version > 4 to avoid the issue described in #18 and remove the travis workaround.
Closes #18

Remove pyyaml workaround.

---

Dockerfile
hepdata_lib/__init__.py
hepdata_lib/root_utils.py

- restrict ipykernel and ipython versions to work with legacy python
- fix ImageMagick permissions as described in #67 
- some minor changes to make tests pass with recent pytest and pylint versions
Docker container tested locally and confirmed to work.
Closes #68

Fix docker image

---

hepdata_lib/__init__.py

Uncertainty signs should not be restricted as a variation can yield different signs in different parts of he distribution, especially (but not only) when normalized.
I did not check the tests, let's see if it works!

Do not restrict uncertainty signs

---

hepdata_lib/__init__.py

I only found one case where we use `is not`, when we shouldn't. There are some cases where we use something like `is not None`, but as far as I understand, that is fine.
Closes #79

Replace 'is not' with '!=' to compare integers.

---

hepdata_lib/__init__.py
tests/test_variable.py

HepData does not allow qualifiers for independent variables. If you
attempt to add them, the upload to hepdata will crash. We should prevent
users from doing this in the first place.

Disallow qualifiers for independent variables

---

README.md

The link needs a hyphen "-" rather than an underscore "_" to work properly.

Fix pypi badge

---

docs/setup.rst

`mkvirtualenv` is not available, so we need to take this approach.
Also added instructions on what to do when logging back on to lxplus.

fix instructions for CMSSW-based setup on lxplus

---

hepdata_lib/__init__.py
tests/test_variable.py

The `values` property can now be set from the constructor, like:
``var = Variable("name", is_binned=False, values=[1,2,3])``
Additionally, the `values` setter now checks that the input format agrees with the `is_binned` property. If a Variable is binned, the input should be a list of two-valued tuples. If it is not, it should be parse-able into a list of single values.

Improve variable constructor

---

hepdata_lib/__init__.py
tests/test_table.py

Limit the length of table names to 64 characters.

---

.travis.yml
.travis/setup.sh

This makes CI work again on Linux.
Also updating ROOT version to 6.18.00 for MacOS (I accidentally deleted the old version when cleaning up the other day which made the tests fail...).

Patch ImageMagick policy.xml

---

.github/workflows/release.yml
docs/contributing.rst

- Changed push action to use personal access token and updated docs.

Fixed release.yml for protected branches and updated docs

---

.github/workflows/tests.yml

The [homebrew ROOT formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/root.rb) uses `python@3.8` explicitly, so we need to do the same. Installing ROOT from source takes as in the past 45 minutes, so I chose to download a tar ball again.

Fix macOS tests

---

.github/workflows/tests.yml

I think this will fix the failing linuxpy3 tests.

Actions: Make sure to instlal hepdata_lib

---

hepdata_lib/helpers.py
tests/test_helpers.py

All changes in **hepdata_lib/helpers.py**
These functions are mostly utilities to facilitate rounding of values stored in dictionaries as returned, e.g., by RootFileReader::read_hist_1d()
The main one is roundValueAndUncertainty(), which allows to round values according to the significant digits of their respective uncertainties (rounded to a given input precision).

adding functions to manage rounding

---

hepdata_lib/root_utils.py

Tested on ROOT 6.22, 6.20, and 6.18 using LCG_96bpython3, LCG_97apython3, and LCG_98python3, respectively (x86_64-centos7-gcc8 for all three).

ROOT.Double --> ctypes

---

Dockerfile

The setup in the Dockerfile is based on the assumption that the base container is Fedora based. However, apparently root changed their tag structure, so 'latest' does not point to Fedora anymore. They still have specific Fedora tags and switching to that fixes the Docker build. @clelange please check if this makes sense to you

Dockerfile: Make sure to use Fedora-based root container

---

hepdata_lib/__init__.py
hepdata_lib/root_utils.py
tests/test_rootfilereader.py

The main change here is the addition of the ability to read bin labels from ROOT histogram. Tests of the functionality have been added, as well.
While implementing the tests, I realized that many test functions have unnecessarily strict checks of the reader output, which break if you add new keys. I took the opportunity to change these assertions to only check that the data needed for a specific check is present, rather than enforcing that no additional data is present.
I also made two small quality-of-life changes to `Table`.

RootFileReader: Allow access to bin labels + small other improvements

---

hepdata_lib/__init__.py
tests/test_table.py

Functionality related to additional resources has now been separated out into a mixin that is flexible inherited into both Table and Submission. When the Submission object creates the output files, it automatically calls the copy_files method of all tables.
Closes #157

Factor out additional resources, add to Table

---

docs/contributing.rst
docs/dev.rst

- Remove some superfluous white spaces
- document that `wheel` package needs to be installed for building a release (at least it's required for later Python 3 releases)
- Rectify documentation that we're using GitHub Actions and not Travis CI anymore

Minor fixes to docs

---

hepdata_lib/__init__.py
hepdata_lib/helpers.py
setup.py
tests/test_helpers.py
tests/test_submission.py

Fixes #173 
Summary of changes:
* Slight rework of how Submission handles file copying and tar ball creation. Now correctly propagates files from its Table daughters. Added explicit test for this case.
* Small changes forced by new pylint version. Have fixed pylint version now so that it does not keep changing randomly.
* While cleaning up pylint, encountered and fixed small bug in helpers where two functions returned generator objects rather than tuples.

Fix missing file in tar ball

---

docs/requirements.txt

Building the docs is [failing](https://readthedocs.org/projects/hepdata-lib/builds/15522884/) again due to some major version change of sphinx dependencies. Pinning `mistune` version to < 2 should fix this, see e.g. https://github.com/Azure/azure-sdk-for-python/issues/22019#issuecomment-987195928.

Fix building docs

---

docs/requirements.txt
examples/Getting_started.ipynb
examples/combine_limits.ipynb
examples/correlation.ipynb
examples/read_c_file.ipynb
examples/reading_histograms.ipynb
hepdata_lib/__init__.py
requirements.txt
setup.py
tests/test_output.py
tests/test_submission.py
tests/test_table.py
tests/test_utilities.py

With this PR, `Submission.create_files` now automatically calls the hepdata validator on the output file. An AssertionError is thrown if the tar ball is found to be invalid.
Closes #160

Validation of output tarballs 

---

hepdata_lib/__init__.py

Submission.create_files: Set remove_old default to False

---

.github/workflows/tests.yml
README.md
codecov.yml
pyproject.toml
setup.cfg

* Add workflow dispatch option to run on demand.
* Test against Python 3.8 which is the version of Python the ROOT binary was compiled against given the output of `root-config --python-version`.
* Update all GitHub Actions.
* Avoid deprecated direct calls to `python setup.py` and use local pip installs.
* Use `python -m pytest` to add current working directory to `sys.path` as `src/` dir layout not used.
- c.f. https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html
* Run on push events only if to master to let coverage from PRs report properly.
* Use Codecov for reporting coverage.
- Update badge in README to use Codecov [![Coverage Status](https://codecov.io/gh/HEPData/hepdata_lib/graph/badge.svg?branch=master)](https://codecov.io/gh/HEPData/hepdata_lib?branch=master)

ci: Update tests workflow

---

.github/dependabot.yml

Following instructions at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
Later PRs could do the same for Python/pip and maybe also Docker.

Add dependabot config for GitHub actions

---

.github/workflows/documentation-links.yml

Adds https://github.com/readthedocs/actions following https://github.com/simonw/sqlite-utils/blob/main/.github/workflows/documentation-links.yml (only changing the project slug accordingly).

Add readthedocs pull request preview action

---

docs/conf.py
docs/requirements.txt

Unfortunately, this doesn't seem to make the module index work again (see #138), but at least the docs compile again and we're not using outdated/unmaintained packages anymore.
Also, docs review introduced in #202 works nicely (once the docs build and don't fail).
----
:books: Documentation preview :books:: https://hepdata-lib--207.org.readthedocs.build/en/207/

Replace m2r by m2r2 and fix version to 0.3.3

---

hepdata_lib/__init__.py
tests/test_uncertainty.py

Hi! This MR adds more flexibility when dealing with distributions/plots having low non-zero yields: in these cases, due to the limited statistics, it may happen that the uncertainty is symmetric, but the relative value being larger with respect to the nominal value. Therefore, it's a common practice to cap the negative variation at the nominal value to avoid a negative yield, being unphysical.
From a technical point of view, uncertainties are given as asymmetric, but when the up/down variations have opposite sign only, thus sharing the same magnitude, they are considered as symmetric. On the other hand, nothing changes for asymmetric ones. So, the resulting _yaml_ file will have symmetric or asymmetric uncertainties accordingly, improving general readability in case of mixed entries. …

Dealing with symmetric and asymmetric uncertainties at the same time

---

.github/workflows/tests.yml

Resolves #200.
Requires #218 to go in first.
* Use the mamba-org/provision-with-micromamba GitHub action to setup a micromamba enviroment with a ROOT version and CPython version defined by the CI matrix.
- Set a default shell of a Bash login to automatically source the micromamba environment.
* Test ROOT v6.24.x and v6.26.x and all compatible Python versions with them.
- Exclude versions of Python that are not compatible with ROOT releases.
- Test on macOS with the latest ROOT release on conda-forge (v6.26.x) and the latest supported CPython version (3.10).
* Install ImageMagick and Ghostscript through conda-forge.
* Remove commented out macOS and Python 2.7 workflows.
----
:books: Documentation preview :books:: https://hepdata-lib--220.org.readthedocs.build/en/220/

ci: Use micromamba to test Python and ROOT

---

setup.py

Add requires-python metadata through the addition of setuptools's python_requires in setup.py.
- c.f. https://peps.python.org/pep-0621/#requires-python
The lower bound versions are selected to support the versions of CPython currently supported: 2.7 and 3.6+. Currently these lower bound versions of CPython (2.7, 3.6) have all reached EOL:
```console
$ python -m pip install --upgrade norwegianblue
$ eol python
┌───────┬────────────┬─────────┬────────────────┬────────────┐
│ cycle │  release   │  latest │ latest release │    eol     │
├───────┼────────────┼─────────┼────────────────┼────────────┤
│  3.11 │ 2022-10-24 │  3.11.2 │   2023-02-07   │ 2027-10-24 │
│  3.10 │ 2021-10-04 │ 3.10.10 │   2023-02-07   │ 2026-10-04 │
│  3.9  │ 2020-10-05 │  3.9.16 │   2022-12-06   │ 2025-10-05 │
│  3.8 …
```

build: Add requires-python metadata

---

.github/workflows/tests.yml
hepdata_lib/__init__.py
hepdata_lib/c_file_reader.py
hepdata_lib/helpers.py
hepdata_lib/root_utils.py
setup.py
tests/test_cfilereader.py
tests/test_execute_command.py
tests/test_helpers.py
tests/test_notebooks.py
tests/test_output.py
tests/test_rootfilereader.py
tests/test_submission.py
tests/test_table.py
tests/test_uncertainty.py
tests/test_utilities.py
tests/test_variable.py

Now that `hepdata_lib` is Python 3.6+, apply some code cleaning by upgrading all syntax to use modern Python that is Python 3.6+ compliant by applying `pyupgrade --py36-plus` to the codebase.
Requires PR #221 to go in first.

chore: Apply pyupgrade --py36-plus

---

docs/conf.py
docs/dev.rst

Docs are failing to build because there's no SVG support, see an example log at https://readthedocs.org/api/v2/build/22295173.txt
This is an attempt to fix the issue, following https://github.com/sphinx-doc/sphinx/issues/1907
----
:books: Documentation preview :books:: https://hepdata-lib--240.org.readthedocs.build/en/240/

Add sphinx.ext.imgconverter extension to make SVGs build in LateX

---

README.md
examples/reading_scikihep_histograms.ipynb
hepdata_lib/hist_utils.py
requirements.txt
tests/test_histread.py

- Adding the scikit-hep histograms conversion function 
- Adding help function to simplify the Table/Variable declaration
- Properly add test cases
----
:books: Documentation preview :books:: https://hepdata-lib--243.org.readthedocs.build/en/243/

Converting from scikit-hep histogram to Table

---

README.md
docs/setup.rst

By now most sites will have moved to Apptainer and even though `singularity` is typically soft-linked to `apptainer`, using `SINGULARITY_CACHEDIR` instead of `APPTAINER_CACHEDIR` will lead to a warning, so updating the docs is better.
----
:books: Documentation preview :books:: https://hepdata-lib--244.org.readthedocs.build/en/244/

Update docs to use Apptainer instead of Singularity

---

.github/workflows/tests.yml

Following https://github.com/mamba-org/provision-with-micromamba?tab=readme-ov-file#example-2-micromamba-version-environment-file-false-channels
Also fixes upload-artifact https://github.com/actions/upload-artifact/tree/v4/?tab=readme-ov-file#not-uploading-to-the-same-artifact
----
📚 Documentation preview 📚: https://hepdata-lib--249.org.readthedocs.build/en/249/

Migrate test action to setup-micromamba and fix upload-artifact

---

docs/usage.rst
hepdata_lib/__init__.py
tests/test_uncertainty.py

* Add a [paragraph](https://hepdata-lib--251.org.readthedocs.build/en/251/usage.html#uncertainties) to the documentation to explain how to encode missing bins.
* Add an option `zero_uncertainties_warning` to the `Variable` class with default value `True`.
* Add a test for a data point with zero uncertainties.  This should have been added as part of PR #161.
* In response to #247.
----
📚 Documentation preview 📚: https://hepdata-lib--251.org.readthedocs.build/en/251/

Clarify behaviour if zero uncertainties

---

README.md
docs/dev.rst
docs/setup.rst
examples/Getting_started.ipynb

The "SWAN-specific instructions" at the top of [Getting_started.ipynb](https://github.com/HEPData/hepdata_lib/blob/main/examples/Getting_started.ipynb) are misleading as they imply that `hepdata_lib` needs to be installed.  Moreover, the given command `pip install --user hepdata_lib` does not work to upgrade `hepdata_lib` without setting a `$PYTHONPATH` variable in a startup script.  See an email I sent in response to a user query on 22nd January 2024.  I updated the "SWAN-specific instructions" and moved them from the `Getting_started.ipynb` notebook to a new "[Using SWAN](https://hepdata-lib--254.org.readthedocs.build/en/254/setup.html#using-swan)" section in `docs/setup.rst`.  I also printed the `hepdata_lib` version at the top of the `Getting_started.ipynb` notebook so that users can …

Update and move SWAN-specific instructions

---

MANIFEST.in

See https://its.cern.ch/jira/browse/SPI-2507 (access probably restricted).
----
📚 Documentation preview 📚: https://hepdata-lib--255.org.readthedocs.build/en/255/

Include requirements.txt in manifest to fix issues with LCG releases

---

.github/workflows/publish.yml

Fixes #165 
I've added the workflow in PyPI and created the "release" environment following https://til.simonwillison.net/pypi/pypi-releases-from-github
----
📚 Documentation preview 📚: https://hepdata-lib--256.org.readthedocs.build/en/256/

Enable trusted publishing workflow to PyPI

---

docs/usage.rst

Updates the bidirectional linking documentation for records/tables to note that the intended use for the field is not for self-referencing as mentioned in [HEPData/hepdata Issue 765](https://github.com/HEPData/hepdata/issues/765)
----
📚 Documentation preview 📚: https://hepdata-lib--258.org.readthedocs.build/en/258/

Update usage.rst to include self-referencing notice

---

.github/workflows/tests.yml
README.md
docs/dev.rst
hepdata_lib/c_file_reader.py
hepdata_lib/root_utils.py
pyproject.toml
setup.py
tests/test_cfilereader.py
tests/test_notebooks.py
tests/test_rootfilereader.py
tests/test_utilities.py

* Print out an error message if ROOT cannot be imported.
* Add some explanation at the end of the README.md file.
* Correct a typo in the link to `reading_scikithep_histograms.ipynb`.
* Add a Pytest [custom marker](https://docs.pytest.org/en/7.1.x/example/markers.html) to test functions requiring ROOT.
* Allow CI to run subset of tests without ROOT using `pytest -m 'not needs_root'`.
* Closes #99.
----
📚 Documentation preview 📚: https://hepdata-lib--259.org.readthedocs.build/en/259/

Add `try`/`except` around ROOT import

---

README.md

Resolves https://github.com/HEPData/hepdata_lib/issues/117
following https://github.com/conda-forge/staged-recipes/pull/26293 and https://github.com/conda-forge/hepdata-lib-feedstock/
* Add conda-forge install instructions to README.
* Add badge for conda-forge distribution to README. [![conda-forge version](https://img.shields.io/conda/vn/conda-forge/hepdata-lib.svg)](https://prefix.dev/channels/conda-forge/packages/hepdata-lib)
- c.f. https://anaconda.org/conda-forge/hepdata-lib
- Use prefix.dev's view as it provides much better user information.
----
📚 Documentation preview 📚: https://hepdata-lib--262.org.readthedocs.build/en/262/

docs: Add conda-forge install instructions and badge to README

---

.github/workflows/tests.yml

https://github.com/HEPData/hepdata_lib/blob/ba9f2e28e33e59bb2bf5b429cab97d31cd556538/.github/workflows/tests.yml#L144-L148
I noticed in PR #265 that the CI is successful for commit 81adb429876820762c6b8608b9f36cc69d1040e9 ([workflow run](https://github.com/HEPData/hepdata_lib/actions/runs/10041588892)) despite the command `python -m pylint hepdata_lib/*.py` giving a exit code 8 with a message:
```
************* Module hepdata_lib
hepdata_lib/__init__.py:237:4: R0912: Too many branches (13/12) (too-many-branches)
-----------------------------------
Your code has been rated at 9.99/10
```
Thus it looks like only the second command `python -m pylint tests/*.py` giving `Your code has been rated at 10.00/10` (exit code 0) determines whether the "Run pylint" step passes or fails.  The …

Use separate Pylint steps in CI for `hepdata_lib` and `tests` directories

---

docs/usage.rst
hepdata_lib/__init__.py
hepdata_lib/helpers.py
tests/test_uncertainty.py

Proposal solution for the feature discussed in #229 :
The HepData validator already allows for cases where different bins have different error breakdowns, but `hepdata_lib` currently does not support this.
With this change set one can suppress individual sources by setting them to `None`.
Closes #266.
----
📚 Documentation preview 📚: https://hepdata-lib--265.org.readthedocs.build/en/265/

Add support for inhomogenous error breakdowns

---

README.md
docs/setup.rst

This should also improve consistency between README and general docs.
----
📚 Documentation preview 📚: https://hepdata-lib--268.org.readthedocs.build/en/268/

Add more details on Apptainer usage to setup/getting started docs

---

docs/conf.py
docs/contributing.rst
docs/dev.rst

Release creation is automated via GitHub actions but this is not yet reflected in the documentation.
----
📚 Documentation preview 📚: https://hepdata-lib--269.org.readthedocs.build/en/269/

Update release creation docs

---

hepdata_lib/__init__.py
tests/test_submission.py
tests/test_table.py

Fixes #272 
----
📚 Documentation preview 📚: https://hepdata-lib--273.org.readthedocs.build/en/273/

Require named arguments to fix pylint too-many-positional-arguments

---

.github/workflows/tests.yml
.gitignore
README.md
hepdata_lib/c_file_reader.py
hepdata_lib/root_utils.py
setup.py

* Closes #276.
* The test matrix is also expanded to include ROOT 6.32/6.34 and Python 3.12/3.13.
----
📚 Documentation preview 📚: https://hepdata-lib--277.org.readthedocs.build/en/277/

Remove warning importing ROOT in `root_utils.py` and expand test matrix

---

docs/usage.rst
hepdata_lib/root_utils.py
tests/test_rootfilereader.py

Adds a function to read in TEfficiency by creating a TGraph and feeding that into the existing TGraph reader.
----
📚 Documentation preview 📚: https://hepdata-lib--275.org.readthedocs.build/en/275/

Add function to read TEfficiency

---

hepdata_lib/__init__.py
hepdata_lib/c_file_reader.py
hepdata_lib/root_utils.py
requirements.txt
tests/test_utilities.py

`raise ... from` is available since forever?, so no need for keeping the obsolete future module
The future package relies on 2to3, which was removed in python 3.13. We want to get rid of the future package in the LCG stacks for python 3.13
----
📚 Documentation preview 📚: https://hepdata-lib--283.org.readthedocs.build/en/283/

Remove requirement of the future package
