HEPData/hepdata_lib

hepdata_lib/__init__.py, setup.py
=> Remove unicode literals

docs/_static/observables.html, docs/_static/partlist.html, docs/_static/phrases.html, docs/conf.py, docs/observables.rst, docs/partlist.rst, docs/phrases.rst, docs/requirements.txt
Closes #7 
Also switch to a fancier theme.
=> Add HEPData documents to documentation

.travis.yml, .travis/setup.sh, README.md
Add tests for osx with python3 and linux (Ubuntu 14) with python2.7
Results: https://travis-ci.org/clelange/hepdata_lib/builds/372042720
=> first travis CI attempt

hepdata_lib/__init__.py, tests/test_variable.py
Function performs checks on input.
=> Variable: add 'add_uncertainty' function + test

hepdata_lib/__init__.py, tests/test_rootfilereader.py, tests/test_utilities.py
* Added reader for TH1
* TH2 reader now also returns bin errors
* Tests for both
=> RootFileReader: Read TH1, improve TH2 reading + tests

.gitignore, hepdata_lib/__init__.py, tests/test_rootfilereader.py, tests/test_submission.py, tests/test_table.py
=> Improve logic of table output file creation

docs/contributing.rst, docs/index.rst
- how to use bumpversion
- how to upload to PyPI
Closes #13 
Closes #6
=> Add developer documentation

hepdata_lib/__init__.py, tests/test_execute_command.py
- issue warning in this case
- add tests for execute_command
Closes #41
=> create Submission even if ImageMagick is not installed

README.md
Accidentally pointed to the wrong URL.
=> fix SWAN link

hepdata_lib/__init__.py, setup.py, tests/test_submission.py, tests/test_table.py
Closes #51 
@AndreasAlbert and @rappoccio - can you try with your setup and make sure the files come out fine?
=> New defaultdict representer

hepdata_lib/__init__.py, tests/test_rootfilereader.py, tests/test_utilities.py
Added input checks and wrote test.
=> RootFileReader: Improve and test read_tree function

hepdata_lib/root_utils.py
This is a pretty simple change that is necessary to handle axes with nonuniform bin edges.
=> Fixed typo affecting calculation of y_edges.

hepdata_lib/__init__.py, tests/test_rootfilereader.py, tests/test_submission.py, tests/test_utilities.py
=> Add more testing for RootFileReader class

.bumpversion.cfg, hepdata_lib/__init__.py
Make pylint happy again and tests pass.
=> remove trailing whitespace, add __version__ property

docs/usage.rst
* Add documentation for binned Variables
* Add documentation for Tables with multiple independent variables (i.e. 2D plots)
* Clarify role of `submission` folder in documentation
* Update hyperlinks to reflect Github URL change (`clelange` -> `HEPData`)
Closes #88
=> Improve documentation

hepdata_lib/__init__.py
=> Increase image file resolution.

docs/dev.rst, docs/index.rst
=> Add testing documentation.

hepdata_lib/helpers.py, tests/test_helpers.py
=> Tuple rounding

.github/workflows/coverage.yml
- Added coverage.yml
- Coveralls did not work on forked pull requests so I changed it to run only when you push.
=> Added coverage.yml github action

.github/workflows/coverage.yml
- Fixed coverage.yml to not run only in master branch
=> Fixed coverage.yml 

.github/workflows/tests.yml, hepdata_lib/__init__.py, setup.py, tests/test_notebooks.py
Issue: Need tests for jupyter notebooks #65
- Added test_notebooks.py file to test notebooks
- Added required libraries in tests.yml
- Fixed linting errors
- Added papermill to test requirements
Closes #65
=> Added notebook tests

.github/workflows/release.yml, docs/contributing.rst
Created release.yml workflow to automatically bump version, create and publish package to PyPI when opening issue. Sends automatic comment on the issue with published version and link to PyPI.
=> Automated the release of hepdata_lib to PyPI

Dockerfile, README.md
- Update Dockerfile to use fedora-based [rootproject/root:latest](https://hub.docker.com/r/rootproject/root)
- Extend README regarding installation into a virtual environment and usage with docker/singularity
Resolves #132
=> Fix docker image

hepdata_lib/__init__.py, tests/test_output.py
Added test_output.py to test yaml dump. Updated init.py so it registers the required representer.
Closes #110 
Closes #116
=> Added tests for yaml dump

.github/workflows/release.yml
Added "close issue" action at the end of release.yml.
=> Added automatic closing of issues to release.yml

hepdata_lib/c_file_reader.py, tests/test_cfilereader.py
Fixed c_file_reader.py for not being able to read certain valid TGraphErrors.
- Removed unnecessary if statements from create TGraph and TGraphErrors functions
- Added few more test cases.
=> Fixed issue with c_file_reader.py and added tests

.github/workflows/tests.yml
- Divided tests in tests.yml into steps.
- Added steps for converting executed notebooks into .html and saving them as artifacts. Notebooks can be downloaded after the workflow run has completed for preview.
Closes: #124 (Preview notebooks once tested)
=> Improved tests.yml and added notebook previews Closes #124

setup.py
=> Add six as requirement

hepdata_lib/__init__.py, hepdata_lib/helpers.py, tests/test_table.py
=> write_image: Only convert images if target is outdated.

docs/setup.rst
Adding some instruction on how to run the available container using Singularity (see discussion in #186)
=> Add Singularity documentation

docs/conf.py
Trivial change, found this while going through the docs 😄 
----
:books: Documentation preview :books:: https://hepdata-lib--208.org.readthedocs.build/en/208/
=> Update copyright to 2022

docs/setup.rst
Addresses issues observed in #230
----
:books: Documentation preview :books:: https://hepdata-lib--231.org.readthedocs.build/en/231/
=> Update instructions for use with CMSSW
